version: "3.8"

services:
  frontend:
    image: techchallengefiap/techchallenge3-frontend
    container_name: frontend-blog-escola-publica
    restart: always
    ports:
      - "80:80"
  api:
    image: jefoso/blog-escola-publica
    container_name: app-blog-escola-publica
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      JWT_SECRET: ${JWT_SECRET}
  mongodb:
    image: mongo:latest
    container_name: db-blog-escola-publica
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      

volumes:
  mongodb_data:
    driver: local
